services:
  discord_ai_bot-5.1:
    build: .
    container_name: discord_ai_bot-5.1
    restart: always
    environment:
      - DISCORD_BOT_TOKEN=${DISCORD_BOT_TOKEN}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_GENAI_API_KEY=${GOOGLE_GENAI_API_KEY}
      - CLAUDE_API_KEY=${CLAUDE_API_KEY}
      - GROK_API_KEY=${GROK_API_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - API_SECRET_KEY=${API_SECRET_KEY}
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
    volumes:
      - ./data:/app/data
      - discord_bot_logs:/app/logs
    ports:
      - "${DASHBOARD_PORT:-8050}:8050"

# Define named volumes for data persistence
volumes:
  discord_bot_logs:
    driver: local
