version: '3.8'

services:
  discord-bot:
    build: .
    container_name: discord_bot
    volumes:
      - ./:/app
    env_file:
      - .env
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:6.2
    container_name: redis
    restart: unless-stopped
